// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgfdetkdtqwmacvnjlpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnZmRldGtkdHF3bWFjdm5qbHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTY1NDYsImV4cCI6MjA2ODA3MjU0Nn0.QiS_5WnqXF9AF4scUP5nKcotDnnr4yWndXE9HmfusT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});